# Generated by Django 4.2 on 2024-10-31 12:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.CharField(max_length=20, unique=True, verbose_name='telegram id')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('group', models.CharField(max_length=150, null=True, verbose_name='group')),
                ('type', models.CharField(choices=[('STUDENT', 'Student'), ('ANOTHER', 'Another'), ('EMPLOYEE', 'Employee')], default='ANOTHER', max_length=8, verbose_name='type')),
            ],
            options={
                'verbose_name': 'requested user',
                'verbose_name_plural': 'requested users',
            },
        ),
        migrations.CreateModel(
            name='RequestedUserMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True, verbose_name='xabar')),
                ('request_type', models.IntegerField(choices=[(1, 'Get a login password for the Internet'), (2, 'Kerio login password recovery')], verbose_name='request type')),
                ('requested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeal.requesteduser', verbose_name='requested user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
